version: 0.0
os: linux
files:
  - source: /target/::JAR_FILE::
    destination: /opt/talytica/application/builds
hooks:
  AfterInstall:
    - location: deploy/stop.sh
      timeout: 300
      runas: root
    - location: deploy/deploy-latest.sh
      timeout: 300
      runas: root
    - location: deploy/start.sh
      timeout: 300
      runas: root
